finance/currencies/urls.py
from django.urls import path
from . import views

app_name = 'currencies'
urlpatterns = [
    path('',views.home,name='home'),
    
    path('asset/',views.asset_home,name='asset_home'),
    path('asset/<slug:slug>/',views.asset,name='asset'),

    path('symbol/',views.symbol_home,name='symbol_home'),
    path('symbol/<slug:slug>/',views.symbol,name='symbol'),

]

finance/finance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from currencies import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('currencies/',include('currencies.urls')),
    path('qtrading/',include('qtrading.urls')),
    path('reuser/',include('reuser.urls')),
    path('',views.home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/qtrading/urls.py
from django.urls import path
from . import views

app_name = 'qtrading'
urlpatterns = [
    path('',views.qtrading,name='qtrading'),
    path('create_qtrading/',views.create_qtrading,name='create_qtrading'),
    path('qtrading_info/<slug:slug>/',views.qtrading_info,name='qtrading_info'),

    path('trade/',views.trade,name='trade'),

    path('buy_or_sell/',views.buy_or_sell,name='buy_or_sell'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('ceshi/',views.ceshi,name='ceshi'),
] 

finance/reuser/urls.py
from django.urls import path
from . import views

app_name = 'reuser'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('activation/',views.activation,name='activation'),
    path('userview/',views.userview,name='userview'),
]

finance/currencies/models.py
from django.db import models
from reuser.models import ReUser
# Create your models here.

#币种信息
class Asset(models.Model):
	name = models.CharField(max_length=100,primary_key=True)
	full_name = models.CharField(max_length=100)
	price = models.FloatField()
	change_24h = models.FloatField(null=True, blank=True) #价格涨幅
	market_cap = models.FloatField() #总市值
	#total_issued = models.CharField(max_length=100) #总发行
	#quantity_of_circulation  = models.CharField(max_length=100) #市场流通量
	#issue_price = models.FloatField(null=True, blank=True) #发行价格
	#issue_priceChangePercent = models.FloatField(null=True, blank=True)  #发行价格变动百分比
	#issue_date = models.DateTimeField(null=True, blank=True) #发行日期
	#website = models.URLField(null=True) #网址
	#introduce = models.TextField() 
	logo = models.ImageField(upload_to='AssetLogo',blank=True,default='AssetLogo/default/default.png') 
	data_update_time = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.asset_name

#充值提取明细
class DepositDetails(models.Model):
	account = models.ForeignKey(ReUser,null=True,on_delete=models.CASCADE)
	amount = models.FloatField() #量
	address = models.CharField(max_length=100) #地址
	addressTag = models.CharField(null=True,max_length=100)
	txId = models.CharField(max_length=100,primary_key=True)
	asset = models.ForeignKey(Asset,null=True,on_delete=models.CASCADE)
	status = models.BooleanField(default=False)
	insertTime = models.DateTimeField(auto_now_add=True)

#市场信息
class SymbolInfo(models.Model):
	symbol = models.CharField(max_length=100,primary_key=True)
	baseAssetPrecision = models.SmallIntegerField()
	quotePrecision = models.SmallIntegerField()
	
	baseAsset = models.CharField(max_length=100)
	quoteAsset = models.CharField(max_length=100)
	
	minPrice = models.FloatField()
	maxPrice = models.FloatField()
	tickSize = models.FloatField() #价格最小步数
	minQty = models.FloatField()
	maxQty = models.FloatField()
	stepSize =models.FloatField() #数量最小步数

	status = models.CharField(max_length=100)
	#serverTime = models.DateTimeField()
	#price = models.FloatField(null=True)
	#volatility = models.FloatField(null=True,default=0)
	data_update_time = models.DateTimeField(auto_now=True)

#用户资产情况
class AccountInfo(models.Model):
	account = models.ForeignKey(ReUser,null=True,on_delete=models.CASCADE)
	asset = models.ForeignKey(Asset,null=True,on_delete=models.CASCADE) 
	total = models.FloatField(null=True) #总持有量
	free = models.FloatField(null=True)	#可使用
	locked = models.FloatField(null=True) #冻结
	
	cost_price = models.FloatField(null=True,default=0) #成本单价
	cost  = models.FloatField(null=True,default=0) #成本
	market_value = models.FloatField(null=True,default=0) #当前市值
	profit_and_loss = models.FloatField(null=True,default=0) #变动
	p_a_l_percent = models.FloatField(null=True,default=0) #变动百分百
	
	data_update_time = models.DateTimeField(auto_now=True)	

class Ticker24(models.Model):
	symbol = models.CharField(max_length=10,null=True)
	askPrice = models.FloatField()
	bidPrice = models.FloatField()
	askQty = models.FloatField()
	bidQty = models.FloatField()
	lastQty = models.FloatField()

	firstId = models.CharField(max_length=10)
	lastId = models.CharField(max_length=10)
	
	openPrice = models.FloatField()
	lowPrice = models.FloatField()
	highPrice = models.FloatField()
	lastPrice = models.FloatField()

	volume = models.FloatField()
	quoteVolume = models.FloatField()

	priceChange = models.FloatField()
	priceChangePercent = models.FloatField()

	count = models.FloatField()
	prevClosePrice = models.FloatField()
	weightedAvgPrice = models.FloatField() #加权平均价格

	openTime = models.DateTimeField()
	closeTime = models.DateTimeField()

finance/currencies/views.py
from django.shortcuts import render
from currencies.models import Asset,DepositDetails,SymbolInfo,AccountInfo,Ticker24
from qtrading.models import Qtrading,Order,Trade
# Create your views here.
from binance.client import Client
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required 
import json

def home(request):
    context ={}
    context['Ticker24'] = Ticker24.objects.all().order_by('-priceChangePercent')
    return render(request,'home.html',context) 
    

def asset_home(request):
    context ={}

    context['assets'] = Asset.objects.all().order_by('-market_cap')
    return render(request,'asset/asset_home.html',context)
    
def asset(request):
    pass
    

def symbol_home(request):
    context = {}

    context['symbols'] = SymbolInfo.objects.all().order_by('-quoteAsset')
    return render(request,'symbol/symbol_home.html',context)

@csrf_exempt
def symbol(request,slug):
    context = {}
    api_key = "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A"
    api_secret = "NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j"
    client = Client(api_key, api_secret)
 
    ifo = client.get_historical_klines(slug, Client.KLINE_INTERVAL_1DAY, "60 day ago UTC")
    context['ifo'] = json.dumps(ifo)
    context['symbol'] = SymbolInfo.objects.get(symbol=slug)
    if request.user.is_authenticated:
        context['q_trading_list'] = Qtrading.objects.filter(account=request.user,symbol_id=slug,iswork=True)
    return render(request,'symbol/symbol.html',context)



'''
    #保存exchan_info----------------
    api_key = 'fkcX35mJZoBwEEKgAT7hFd9R3bnD4iw6WSUJJijKC27RaO94b6IIuvU15WIP1R3R'
    api_secret = '6FnpYJluhtZn2YpJRyBK9INmokG0mv8XgNgqcMFUBLLmm40B2N9PjYppcVDbV2UX'

    client = Client(api_key, api_secret)
    exchangeinfo = client.get_exchange_info()
    for each in exchangeinfo['symbols']:
        symbol=each['symbol']
        baseAssetPrecision = each['baseAssetPrecision']
        quotePrecision =each['quotePrecision']
        status=each['status']
        baseAsset =each['baseAsset']
        quoteAsset = each['quoteAsset']
        minPrice = each['filters'][0]['minPrice']
        maxPrice = each['filters'][0]['maxPrice']
        tickSize =each['filters'][0]['tickSize']
        maxQty = each['filters'][1]['maxQty']
        minQty = each['filters'][1]['minQty']
        stepSize= each['filters'][1]['stepSize']

        exifo=SymbolInfo(symbol=symbol,baseAssetPrecision=baseAssetPrecision,quotePrecision=quotePrecision,
            status=status,baseAsset=baseAsset,quoteAsset=quoteAsset,minPrice=minPrice,maxPrice=maxPrice,
            tickSize=tickSize,maxQty=maxQty,minQty=minQty,stepSize=stepSize)
        exifo.save()
    #--------------------------------
'''

finance/currencies/templates/symbol/symbol.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{symbol.symbol}} {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'amcharts/export.css'%}" type="text/css" media="all" />
{% endblock %}

{% block content%}
    <h1>
        {{symbol.baseAsset}}/{{symbol.quoteAsset}}
    </h1>

    <div id="list"></div>

    <div id="chartdiv" style="width:100%; height:500px;"></div>
    <br>
    {%if user.is_authenticated%}
    <div class="row"> 
        <div class="col-md-6" align="center" >
          <div class="form-horizontal"  >  
            <div style="border:3px solid rgb(219, 76, 60);padding: 20px;margin-bottom: 10px; ">
                <b align="center" style="color:rgb(219, 76, 60) ">买入{{symbol.baseAsset}}</b> 
                <div>
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="">价格</span>
                      </div>
                      <input type="number" class="form-control" id="b_p"  min="0" step="0.000001" >
                    </div>
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="">总支付</span>
                      </div>
                      <input type="number" class="form-control" id="b_t"  min="0" step="0.000001" name="start_price">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="">USDT</span>
                      </div>
                    </div>
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="-sizing-sm">量化操作</span>
                      </div>
                      <select class="form-control" id="buy_limit" name="buy_limit">
                           <option value=''>默认不计入</option>
                           {% for each in q_trading_list %}
                           <option value='{{each.id}}'>{{each.q_name}}</option>
                           {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="btn-group" role="group" aria-label="Third group">
                  <button  class="btn btn-block" style="background-color:rgb(219, 76, 60);color: white " id="buy">买入</button>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 " align="center">
          <div class="form-horizontal"  >
            <div style="border:3px solid rgb(127, 141, 169);padding: 20px;margin-bottom: 10px; ">
                <b align="center" style="color:rgb(127, 141, 169) ">卖出{{symbol.baseAsset}}</b>
                <div>
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="-sizing-sm">价格</span>
                      </div>
                      <input type="number" class="form-control" id="s_p" min="0" step="0.000001" name="start_price">
                    </div>
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="-sizing-sm">总支付</span>
                      </div>
                      <input type="number" class="form-control" id="s_t" min="0" step="0.000001" name="start_price">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="">USDT</span>
                      </div>
                    </div>
                    
                    <div class="input-group input-group-sm mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="-sizing-sm">量化操作</span>
                      </div>
                      <select class="form-control" id="sell_limit" name="sell_limit">
                           <option value=''>默认不计入</option>
                           {% for each in q_trading_list %}
                           <option value='{{each.id}}'>{{each.q_name}}</option>
                           {% endfor %}
                        </select>
                    </div>


                </div>
                <div class="btn-group" role="group" aria-label="Third group">
                  <button class="btn btn-block" style="background-color:rgb(127, 141, 169);color: white " id="sell">卖出</button>
                </div>
            </div>
          </div>
        </div>
    </div>
    {%else%}
    <div style="border:3px solid rgb(219, 76, 60);padding: 20px;margin-bottom: 10px;text-align: center;">
      <span><b><a href="">登录</a>/<a href="">注册</a></b> 后进行买卖下单操作</span>
    </div>
    {%endif%}
{% endblock %}

{% block script%}
<script src="{% static 'amcharts/amcharts.js'%}"></script>
<script src="{% static 'amcharts/serial.js'%}"></script>
<script src="{% static 'amcharts/amstock.js'%}"></script>
<script src="{% static 'amcharts/export.min.js'%}"></script>

<script>
    AmCharts.ready(function () {
        generateChartData();
        createStockChart();
        addPanel();
    });

    var chart;
    var chartData = [];
    var newPanel;
    var stockPanel;
    
    function generateChartData() {
        var firstDate = new Date();
        firstDate.setHours(0, 0, 0, 0);
        firstDate.setDate(firstDate.getDate() - 2000);

        var aaaaaa = {{ifo|safe}};
        var aaa=(aaaaaa);

        for (var i = 0; i < aaa.length; i++) {
            var cdate = aaa[i][0];
            var copen = aaa[i][1];
            var cclose = aaa[i][4];
            var chigh = aaa[i][2];
            var clow = aaa[i][3];
            var cvolume = aaa[i][5];

            
            chartData.push ({
                date: cdate,
                open: copen,
                close: cclose,
                high: chigh,
                low: clow,
                volume: cvolume
            });             
        };                  
    };

        
    function createStockChart() {
        chart = new AmCharts.AmStockChart();

        chart.balloon.horizontalPadding = 10;

        // DATASET //////////////////////////////////////////
        var dataSet = new AmCharts.DataSet();
        dataSet.fieldMappings = [{
            fromField: "open",
            toField: "open"
        }, {
            fromField: "close",
            toField: "close"
        }, {
            fromField: "high",
            toField: "high"
        }, {
            fromField: "low",
            toField: "low"
        }, {
            fromField: "volume",
            toField: "volume"
        }, {
            fromField: "value",
            toField: "value"
        }];
        dataSet.color = "#7f8da9";
        dataSet.dataProvider = chartData;
        dataSet.categoryField = "date";

        chart.dataSets = [dataSet];

        // 股票面板
        stockPanel = new AmCharts.StockPanel();
        stockPanel.title = "Value";

        // 股票图
        var graph = new AmCharts.StockGraph();
        graph.type = "candlestick";
        graph.openField = "open";
        graph.closeField = "close";
        graph.highField = "high";
        graph.lowField = "low";
        graph.valueField = "close";
        graph.lineColor = "#7f8da9";
        graph.fillColors = "#7f8da9";
        graph.negativeLineColor = "#db4c3c";
        graph.negativeFillColors = "#db4c3c";
        graph.fillAlphas = 1;
        graph.balloonText = "open:<b>[[open]]</b><br>close:<b>[[close]]</b><br>low:<b>[[low]]</b><br>high:<b>[[high]]</b>";
        graph.useDataSetColors = false;
        stockPanel.addStockGraph(graph);

        //股票图例
        var stockLegend = new AmCharts.StockLegend();
        stockLegend.markerType = "none";
        stockLegend.markerSize = 0;
        stockLegend.valueTextRegular = undefined;
        stockLegend.valueWidth = 250;
        stockPanel.stockLegend = stockLegend;

        chart.panels = [stockPanel];

        // 图表滚动条设置
        var sbsettings = new AmCharts.ChartScrollbarSettings();
        sbsettings.graph = graph;
        sbsettings.graphType = "line";
        sbsettings.usePeriod = "WW";
        chart.chartScrollbarSettings = sbsettings;

        // 面板设置
        var panelsSettings = new AmCharts.PanelsSettings();
        panelsSettings.panEventsEnabled = true;
        chart.panelsSettings = panelsSettings;

        // 游标设置
        var cursorSettings = new AmCharts.ChartCursorSettings();
        cursorSettings.valueBalloonsEnabled = true;
        cursorSettings.fullWidth = true;
        cursorSettings.cursorAlpha = 0.1;
        chart.chartCursorSettings = cursorSettings;

        // 期间选择器
        var periodSelector = new AmCharts.PeriodSelector();
        periodSelector.position = "bottom";
        periodSelector.periods = [{
            period: "DD",
            count: 10,
            label: "10 days"
        }, {
            period: "MM",
            selected: true,
            count: 1,
            label: "1 month"
        }, {
            period: "YYYY",
            count: 1,
            label: "1 year"
        }, {
            period: "YTD",
            label: "YTD"
        }, {
            period: "MAX",
            label: "MAX"
        }];
        chart.periodSelector = periodSelector;


        chart.write('chartdiv');
    }

    function addPanel() {
        newPanel = new AmCharts.StockPanel();
        newPanel.allowTurningOff = true;
        newPanel.title = "Volume";
        newPanel.showCategoryAxis = false;

        var graph = new AmCharts.StockGraph();
        graph.valueField = "volume";
        graph.fillAlphas = 0.5;
        graph.type ='column'
        newPanel.addStockGraph(graph);

        var legend = new AmCharts.StockLegend();
        legend.markerType = "none";
        legend.markerSize = 0;
        newPanel.stockLegend = legend;
        newPanel.percentHeight=30;

        chart.addPanelAt(newPanel, 1);
        chart.validateNow();

    }

</script>

<script type="text/javascript">
  //下订单 js
  $("#buy").click(function(){
    if(confirm("确认买入?")){
      var b_p= $("#b_p").val();
      var b_t= $("#b_t").val();
      var q_trading =$("#buy_limit").val();
      var data_ = {'b_p':b_p,'b_t': b_t,"symbol":'{{symbol.symbol}}',"q_trading":q_trading} ;
      $.post("{%url 'qtrading:buy_or_sell'%}",data_,function(response_date){  
          if (response_date.orderId){
            alert('卖单'+response_date.orderId+'已建立！');
          }
          else if (response_date.aa){alert('卖单建立失败!');};
      });
    } 
    $('#b_p').val("");
    $('#b_t').val("");

  });

  $("#sell").click(function(){
    if(confirm("确认卖出?")){
      var s_p= $("#s_p").val();
      var s_t= $("#s_t").val();
      var q_trading =$("#sell_limit").val();
      var data_ = {'s_p':s_p,'s_t': s_t,"symbol":'{{symbol.symbol}}',"q_trading":q_trading} ;
      $.post("{%url 'qtrading:buy_or_sell'%}",data_,function(response_date){  
          if (response_date.orderId) {
            alert('卖单'+response_date.orderId+'已建立！');
          }
          else if (response_date.aa){alert('卖单建立失败!');};
      });
    } 
    $('#s_p').val("");
    $('#s_t').val("");
  });
</script>
{% endblock %}

finance/currencies/templates/symbol/symbol_home.html
{%extends 'base.html' %}
{% load static %}

{% block title %} symbol {% endblock %}

{% block content%}

<table class="table table-sm table-hover ">
		<thead class="">
			<tr>
				<th scope="col">#</th>
				<th scope="col">市场</th>
				<th scope="col">baseAsset</th>
				<th scope="col">quoteAsset</th>


			</tr>
		</thead>
		<tbody>
			{% for each in symbols %}
			<tr>
				<th scope="row">{{ forloop.counter }}</th>
				<th><a href="{% url 'currencies:symbol' each.symbol %}">{{each.symbol}}</a>
				<a style="text-decoration:none;color: black" href=""></a></td>
				<td>{{each.baseAsset}}</th>
				<td>{{each.quoteAsset}}</td>
				

			</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}