finance/currencies/urls.py
from django.urls import path
from . import views

app_name = 'currencies'
urlpatterns = [
    path('',views.home,name='home'),
    
    path('asset/',views.asset_home,name='asset_home'),
    path('asset/<slug:slug>/',views.asset,name='asset'),

    path('symbol/',views.symbol_home,name='symbol_home'),
    path('symbol/<slug:slug>/',views.symbol,name='symbol'),

]

finance/finance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from currencies import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('currencies/',include('currencies.urls')),
    path('qtrading/',include('qtrading.urls')),
    path('reuser/',include('reuser.urls')),
    path('',views.home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/qtrading/urls.py
from django.urls import path
from . import views

app_name = 'qtrading'
urlpatterns = [
    path('',views.qtrading,name='qtrading'),
    path('create_qtrading/',views.create_qtrading,name='create_qtrading'),
    path('qtrading_info/<slug:slug>/',views.qtrading_info,name='qtrading_info'),

    path('trade/',views.trade,name='trade'),

    path('buy_or_sell/',views.buy_or_sell,name='buy_or_sell'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('ceshi/',views.ceshi,name='ceshi'),
] 

finance/reuser/urls.py
from django.urls import path
from . import views

app_name = 'reuser'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('activation/',views.activation,name='activation'),
    path('userview/',views.userview,name='userview'),
]

finance/templates/base.html
{% load static %}

<!doctype HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'favicon.jpeg' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--
    <link href="{% static 'js/emojionearea.min.css' %}" rel="stylesheet">
    -->
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/default.css'%}">
    <style type="text/css">
      li.nav-item.avatar{
        margin: auto;
      }
      ul.userinfo:hover .username{
        display:block;
      }
      .nav-item.username{
        display: none;
        box-shadow: 0px 0px 20px rgb(0,0,0,.1);
        
        -webkit-transform: translateX(0%);
          transform: translateX(0%);
          transition: transform 1s linear;
        will-change: transform;
      }

      ul.ul-box{
        list-style: none;
        padding: 0px 5px;
      }
      .page_select{background: #fbd202 !important;color: #fff;}

    </style>

  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark " style="padding:0px;background: #343b40 ">
        <a class="navbar-brand" href="#"><img src="{% static 'favicon.jpeg' %}" style="width:30px;height:30px;margin:0px 15px 0px 15px "></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'currencies:home'  %}">主页 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'currencies:symbol_home' %}">市场</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'currencies:asset_home' %}">币种</a>
            </li>

            <li class="nav-item">
              <a class="nav-link " href="{% url 'reuser:userview' %}">个人账户</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'qtrading:qtrading' %}">量化交易</a>
            </li>
          </ul>

            {% if request.user.is_authenticated%}


            <div class="pull-right  mr-2"  >
              <ul class="navbar-nav mr-auto userinfo">
                <li class="nav-item avatar ">
                  <img id="avatar" src="{{ request.user.avatar.url }}" class="img-circle img-responsive rounded-circle"  style="width:30px;height:30px;">
                </li>
                <li class="nav-item username"><a class="nav-link" >{{request.user.username}}</a></li>
                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'reuser:logout' %}">退出</a>
                </li>
              </ul>
            </div>
            {% else %}
            <div class="pull-right mr-2" >
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                   <a class="nav-link " href="{% url 'reuser:login'  %}" >登录<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                   <a class="nav-link " href="{%url 'reuser:register' %}">注册<span class="sr-only">(current)</span></a>
                </li>
              </ul>
            </div>
            {% endif %}
        </div>
      </nav>
    </header>



    <div class="container" style="min-height: 800px">   
      <br>
      {% block content%}{% endblock %}
    </div>

    <footer class="py-2 "> 
      <div class="text-center">
        <span > 
          <small >&copy; 2018-2018 | weinian</small><br>
          <small >Contact us by email:hanjing@fddiy.com</small>
        </span>

      </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type='text/javascript'>
      CKEDITOR.replace("ckeditor",{ toolbar : [ ['Styles','Format','Font','FontSize'], ['TextColor','BGColor',],
            ['Bold','Italic','Underline','Strike'], 
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','Subscript','Superscript','Smiley'], ] });
    </script>   
    <script src="{% static 'js/emojionearea.min.js' %}"></script>
    -->             
    

    {% block script%}{% endblock %}
  </body>
</html>

finance/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content%}
<div class="card">
  <h5 class="card-header" >24小时市场情况 <span style="font-size: 10px;">数据时间:{{ Ticker24.first.closeTime|date:"m-d H:i:s" }}</span></h5>

  <div class="card-body">
    <div class="panel-body">
    <small>
      <table class="table table-sm table-hover ">
        <thead class="">
          <tr>
            <th scope="col">#</th>
            <th scope="col">市场</th>
            <th scope="col">初始价</th>
            <th scope="col">最高价</th>
            <th scope="col">最低价</th>
            <th scope="col">最后价</th>
            <th scope="col">加权平均价</th>
            <th scope="col">交易量</th>
            <th scope="col">价格变动</th>
            <th scope="col">价格变动率</th>
          </tr>
        </thead>
        <tbody>
          {%for each in Ticker24 %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <th><a  href="{%url 'currencies:symbol' each.symbol %}">{{each.symbol}}</a></td>
            <td>{{each.openPrice}}</td>
            <td>{{each.highPrice}}</td>
            <td>{{each.lowPrice}}</td>
            <td>{{each.lastPrice}}</td>
            <td>{{each.weightedAvgPrice}}</td>
            <td>{{each.volume}}</td>
            <td class="{% if each.priceChange < 0 %}text-danger{% else %}text-success{%endif%}">{{each.priceChange}}</td>
            <td class="{% if each.priceChangePercent < 0 %}text-danger{% else %}text-success{%endif%}">{{each.priceChangePercent}}%</td>
   
          </tr>
          {% endfor %}
    
        </tbody>
      </table>
      </small>
    </div>
  </div>
</div>

{% endblock %}