finance/currencies/urls.py
from django.urls import path
from . import views

app_name = 'currencies'
urlpatterns = [
    path('',views.home,name='home'),
    
    path('asset/',views.asset_home,name='asset_home'),
    path('asset/<slug:slug>/',views.asset,name='asset'),

    path('symbol/',views.symbol_home,name='symbol_home'),
    path('symbol/<slug:slug>/',views.symbol,name='symbol'),

]

finance/finance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from currencies import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('currencies/',include('currencies.urls')),
    path('qtrading/',include('qtrading.urls')),
    path('reuser/',include('reuser.urls')),
    path('',views.home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/qtrading/urls.py
from django.urls import path
from . import views

app_name = 'qtrading'
urlpatterns = [
    path('',views.qtrading,name='qtrading'),
    path('create_qtrading/',views.create_qtrading,name='create_qtrading'),
    path('qtrading_info/<slug:slug>/',views.qtrading_info,name='qtrading_info'),

    path('trade/',views.trade,name='trade'),

    path('buy_or_sell/',views.buy_or_sell,name='buy_or_sell'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('ceshi/',views.ceshi,name='ceshi'),
] 

finance/reuser/urls.py
from django.urls import path
from . import views

app_name = 'reuser'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('activation/',views.activation,name='activation'),
    path('userview/',views.userview,name='userview'),
]

finance/reuser/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

#重置用户信息字段
class ReUser(AbstractUser):
	avatar = models.ImageField(upload_to='AvatarImage',blank=True,default='AvatarImage/default.png')
	apikey = models.CharField(max_length=256,blank=True)
	Secret = models.CharField(max_length=256,blank=True,)

	def __str__(self):
		return self.username

finance/reuser/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth,messages
from django.core.cache import cache
from django.db.models import Q,Count,Sum,functions

from reuser.models import ReUser
from qtrading.models import Qtrading,Order,Trade,CancelStandbyOrders
from currencies.models import Asset,DepositDetails,SymbolInfo,AccountInfo

from django.conf import settings
from django.core.mail import EmailMessage

from binance.client import Client
from binance.exceptions import BinanceAPIException

from reuser.models import ReUser
import finance.utils as utils
from finance.utils import AssistFun
import re

def login(request):
    errors =[]
    username = None
    password = None
    if request.method == "POST":
        if not request.POST.get('username'):
            errors.append('用户名不能为空')
        else:
            username = request.POST.get('username')

        if not request.POST.get('password'):
            errors = request.POST.get('密码不能为空!')
        else:
            password = request.POST.get('password')

        if username is not None and password is not None:
            user = auth.authenticate(username=username,password=password)
            if user :
                auth.login(request,user)
                next_ = request.GET.get('next','/')
                return HttpResponseRedirect(next_)
            else:
                try:
                    ReUser.objects.get(username=username)
                    messages.warning(request,'未激活用户!')
                except:
                    messages.warning(request,'用户名或密码错误!')

    print(request.path)
    return render(request,'login.html',)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/currencies')

def register(request):
    errors = []
    if request.method == 'POST':
        print(request.POST)

        email = request.POST.get('email')
        if len(email)>4 and re.search(r'^[A-Za-z0-9_@.-]+$', email): 
            try:
                ReUser.objects.get(username=email)
                errors.append('邮箱存在，请更换邮箱注册。') 
            except : 
                pass
        else:
            errors.append('用户名有问题，不能注册。字符太少或含用奇怪字符!') 

        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password != password2:
            errors.append('两次输入密码不一致！')

        api_key = request.POST.get('api_key')
        secret = request.POST.get('secret')

        if not errors:   
            user = ReUser.objects.create_user(username=email,password=password,is_active=False)
            user.email = email
            user.apikey = api_key
            user.Secret = secret
            user.save()

            random_str = utils.random_str()
            #cache.set(user.id, random_str, 1*60*60)

            #发送验证邮件---------------------------
            subject, from_email, to_email = '用户激活-伟年科技', settings.DEFAULT_FROM_EMAIL,email
            html_content = utils.activation_html_content(user.id,random_str)

            msg = EmailMessage(subject, html_content, from_email, [to_email])
            msg.content_subtype = "html"  # Main content is now text/html
            msg.send()

            messages.warning(request,'登录您的邮箱，点击激活账号链接！')
            return redirect('reuser:login')

    return render(request,'register.html', {'errors': errors})

@csrf_exempt
def activation(request):
    userid = request.GET.get('userid','')
    random_str = request.GET.get('random_str','')
    if userid and random_str:
        reuser = ReUser.objects.get(id=userid)
        if reuser.is_active:
            messages.warning(request,'此账号已被激活，请登录！')
        else:
            reuser.is_active = True
            reuser.save()
            messages.warning(request,'账号激活完成，请登录！')
        return redirect('reuser:login')
    print(request.GET)


def userview(request):

    context = {}
    symbol_list = ['BNBUSDT','BTCUSDT']
    api_key = request.user.apikey
    api_secret = request.user.Secret

    #try:
    client = Client(api_key, api_secret)

    assf = AssistFun(request.user.id,client,symbol_list)
    #获取订单信息
    assf.all_orders()
    
    #保存存取记录
    assf.all_access()

    #获取交易信息
    assf.all_trading()

    #更新库存信息
    assf.Up_inventory()
   
    
    #更新库存汇总
    #context['undone_orders'] = undone_orders = assf.undone_orders()

    context['total_info'] = assf.totle_inventory()
    context['openoeders'] = Order.objects.filter(account=request.user).filter(Q(status='NEW')|Q(status="PARTIALLY_FILLED")).order_by('-time')
    context['ordering_strem'] = Trade.objects.filter(account=request.user).order_by('-time')[:40]
    context['canceled_orders'] = Order.objects.filter(account=request.user,status='CANCELED').order_by('-time')[:5]
    context['account_info'] = AccountInfo.objects.filter(account=request.user,total__gt=0).order_by('-market_value')


    return render(request,'userview.html',context)

finance/reuser/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}
{% block content %}
    
{% if messages %}
<div class="messages-warning">
    {% for message in messages %}
    <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.message }}</span>
    {% endfor %}
</div>
{% endif %}



<div class="wave-box ">
    <div class='box'>
      <div class='wave -one'></div>
      <div class='wave -two'></div>
      <div class='wave -three'></div>
      <div class='title'>登录</div>
    </div>
    <form class="log" class="form-horizontal container" action=""   method="post">{% csrf_token %} 
        <div class='' style="margin: 30px 0 20px 0;" >
            <input type="text" class="" placeholder="输入用户名" name="username">
            <input type="password" class="" placeholder="输入密码" name="password" >
        </div>
        <div class='d-flex justify-content-center' style="margin: 30px 0 20px 0;" >
            <button type="submit" class="login" >登录</button>
        </div>
    </form>

</div>

<style type="text/css">
  .login{
    width:200px;
    background:#fbd202;
    color: #333;
    padding:6px 12px;
    border: none;
    border-radius: 3px;
    cursor: pointer;
    letter-spacing: .4em;
    font-size: 15px;
  }
  .login:hover{
    box-shadow:3px 3px 20px rgba(150, 150, 150, 0.2);
  }
  button.btn{
    letter-spacing: .4em;
  }
</style>


<style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300);

form.log input {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  outline: 0;
  border: 1px solid #343b40;
  background-color: rgba(255, 255, 255, 0.4);
  width: 200px;
  border-radius: 3px;
  padding: 5px 10px;
  margin: 10px auto;
  display: block;
  text-align: center;
  font-size: 18px;
  color: #343b40;
  transition-duration: 0.25s;
  font-weight: 300;
}
form.log input:hover {
  background-color: rgba(255, 255, 255, 0.4);
}
form.log input:focus {
  background-color: white;
  width: 250px;
  color: #343b40;
}

.wave-box{
  margin: 0 auto;
  top: 50px;
  width: 300px;
  border-radius: 5px;
  box-shadow: 0 2px 30px rgba(0, 0, 0, 0.2);
  position: relative;
  overflow: hidden;
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
}

.box {
  height: 60px;
}
.box:after {
  display: block;
  width: 100%;
  height: 100%;
  z-index: 11;
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
}

.wave {
  justify-content: center;
  opacity: 1;
  position: absolute;
  background: #262d31;
  width: 650px;
  height: 650px;
  left: -180px;
  margin-top: -600px;
  -webkit-transform-origin: 50% 50%;
          transform-origin: 50% 50%;
  border-radius: 45%;
}

.wave.-one {
  -webkit-animation: drift 3000ms infinite linear;
          animation: drift 3000ms infinite linear;
  opacity: 0.2;
  background: #8c876c;
}
.wave.-two {
  -webkit-animation: drift 5000ms infinite linear;
          animation: drift 5000ms infinite linear;
  opacity: 1;
  background: #fbd202;
}

.wave.-three {
  -webkit-animation: drift 7000ms infinite linear;
          animation: drift 7000ms infinite linear;
  background: #343b40;
}


.title {
  position: absolute;
  width: 100%;
  z-index: 1;
  line-height: 60px;
  text-align: center;
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
  color: white;
  letter-spacing: .4em;
  font-size: 25px;
  text-shadow: 0 1px 0 rgba(0, 0, 0, 0.1);
  text-indent: .3em;
}

@-webkit-keyframes drift {
  from {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  from {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes drift {
  from {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  from {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

</style>




{% endblock %}

finance/reuser/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if errors %}
<div class="messages-warning">
	{% for message in errors %}
	<span>{{ message }}</span>
	{% endfor %}
</div>
{% endif %}

{% if messages %}
<div style="border:3px solid rgb(219, 76, 60);padding: 20px;margin-bottom: 10px;text-align: center;">
	{% for message in messages %}
	<span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.message }}</span>
	{% endfor %}
</div>
{% endif %}

<style type="text/css">
	.was-validated{
		width: 50%;
    margin: auto;
   }
  button.btn{
    letter-spacing: .4em;
  }
  .register{
    width:200px;
    background:#fbd202;
    color: #333;
    padding:6px 12px;
    border: none;
    border-radius: 3px;
    cursor: pointer;
    letter-spacing: .4em;
    font-size: 15px;
  }
  .register:hover{
    box-shadow:3px 3px 20px rgba(150, 150, 150, 0.2);
  }


</style>
<div class="form-group">
  <h2><p class="text-center"><span style="text-decoration:line-through;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
	注册 <span style="text-decoration:line-through;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
  </p></h2>
</div>
<div class="jumbotron">
	<form class="was-validated" action=""  enctype="multipart/form-data" method="post">{% csrf_token %}
		<div class="form-group">
			<sanp>邮箱</sanp>
			<input type="email" class="form-control" id="" placeholder="xxx@xxx.com" value="" required name="email" >
		</div>

		<div class="form-group">
			<sanp>密码</sanp>
			<input type="password" class="form-control is-valid" placeholder="" value="" required name="password">
		</div>

		<div class="form-group">
			<sanp>确认密码</sanp>
			<input type="password" class="form-control is-valid"   placeholder="" value="" required name="password2">
		</div>

		<div class="form-group">
			<sanp>API秘钥</sanp>
			<input type="text" class="form-control is-valid"   placeholder="币安api_key" value="" required name="api_key">
		</div>

		<div class="form-group">
			<sanp>秘钥密码</sanp>
			<input type="text" class="form-control is-valid"   placeholder="币安api_key密码(只显示一次,请确认无误)" value="" required name="secret">
		</div>
		<br>
		<div class="form-group" style="text-align: center;">
			<button type="submit" class="btn register" >&nbsp;&nbsp;注册&nbsp;&nbsp;</button>
		</div>
	</form>
</div>



{% endblock %}

finance/reuser/templates/userview.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{request.user.username}} {% endblock %}

{% block content%}

{% if errors %}
<div class="alert alert-danger" role="alert">
  {%for error in errors%}
    {{error}}
  {% endfor %}
</div>
{% else %}
<div>
    <span class="badge badge-light">数据时间:{% now "m-d H:i:s" %}</span>
</div>
{% endif %}

<div>
    <div style="border:1px solid #edf0f2;padding: 20px;margin-bottom: 10px">
    <b>库存</b>
    <table class="table table-sm table-hover ">
      <thead class=""> 
        <tr>
          <th scope="col">等值币种</th>
          <th scope="col">总资产</th>
          <th scope="col">成本</th>
          <th scope="col">除USDT外市值</th>
          <th scope="col">浮动盈亏</th>
          <th scope="col">盈亏比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>USDT</th>
          <td>{{total_info.market_value|floatformat:5}}</td>
          <td>{{total_info.cost|floatformat:5}}</td>
          <td>{{total_info.exclude_usdt|floatformat:5}}</td>
          <td>{{total_info.profit_and_loss|floatformat:5}}</td>
          <td class="{% if total_info.pl_percent < 0 %}text-danger{% else %}text-success{%endif%}">{{total_info.pl_percent|floatformat:2}}%</td>
        </tr>
      </tbody>
    </table>
    <table class="table table-sm table-hover ">
      <thead class="">
        <tr>
          <th scope="col">#</th>
          <th scope="col">币种</th>
          <th scope="col">目前持有</th>
          <th scope="col">可用</th>
          <th scope="col">冻结</th>

          <th scope="col">最新单价</th>
          <th scope="col">目前市值</th>



        </tr>
      </thead>
      <tbody>
        {% for acco in account_info %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <th><a style="text-decoration:none;color: black" href=""><img src="{{acco.asset.logo.url}}" style="width:20px;height:20px"> {{acco.asset.name}}</a></td>
          <td>{{acco.total|floatformat:5}}</td>
          <td>{{acco.free|floatformat:5}}</td>
          <td>{{acco.locked|floatformat:5}}</td>

          <td>{{acco.asset.price|floatformat:5}}</td>
          <td>{{acco.market_value|floatformat:5}}</td>



        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div style="border:1px solid #edf0f2;padding: 20px;margin-bottom: 10px">
  <div>
      <b>当前委托</b>
      <a href="#" class="badge badge-light text-muted" id="cancel_all_orders" style="float:right;"><small>取消当前<span>{{openoeders|length}}</span>个订单</small></a>
    </div>

    <table class="table table-sm table-hover ">
      <thead class="">
        <tr >
          <th scope="col">#</th>
          <th scope="col">市场</th>
          <th scope="col">ID</th>
          <th scope="col">状态</th>
          <th scope="col">买卖</th>
          <th scope="col">价格</th>
          <th scope="col">数量</th>
          <th scope="col">委托金额</th>
          <th scope="col">时间</th>
          <th scope="col">取消订单</th>

        </tr>
      </thead>
      <tbody>
        {% for acco in openoeders %}
        <tr order_id="{{acco.orderId}}">
          <th scope="row">{{ forloop.counter }}</th>
          <th><a symbol_id="{{ forloop.counter }}" style="text-decoration:none;color: black" href="{%url 'currencies:symbol' acco.symbol.symbol %}">{{acco.symbol.symbol}}</a></td>
          <td><p order_id="{{ forloop.counter }}">{{acco.orderId}}</p></td>
          <td>{{acco.status}}</th>
          {% if acco.side == 'SELL'%}
          <td class="text-danger">{{acco.side}}</td>
          {% else %}
          <td class="text-success">{{acco.side}}</td>
          {% endif %}
          <td>{{acco.price|floatformat:5}}</td>
          <td>{{acco.origQty|floatformat:5}}</td>
          <td>{{acco.order_price|floatformat:5}}</td>
          <td>{{acco.time|date:'m-d H:i:s'}}</td>
          <td><button type="button" button_id="{{ forloop.counter }}" class="btn btn-outline-secondary btn-sm">取消订单</button></td>

        </tr>
        {% endfor %}


      </tbody>
    </table>
  </div>

  <div style="border:1px solid #edf0f2;padding: 20px;margin-bottom: 10px">
    <b>历史交易<a href="{%url 'qtrading:trade'%}"><small class="text-muted">(查看所有历史交易)</small></a> </b>
    <small>
    <table class="table table-sm table-hover ">
      <thead class="">
        <tr>
          <th scope="col">#</th>
          <th scope="col">市场</th>
          <th scope="col">ID</th>
          <th scope="col">状态</th>
          <th scope="col">买卖</th>
          <th scope="col">价格</th>
          <th scope="col">数量</th>
          <th scope="col">实际交易金额</th>
          <th scope="col">订单时间</th>
          <th scope="col">交易时间</th>


        </tr>
      </thead>
      <tbody>
        {% for acco in ordering_strem %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <th><a style="text-decoration:none;color: black" href="{%url 'currencies:symbol' acco.order.symbol.symbol %}">{{acco.order.symbol.symbol}}</a></td>
          <td>{{acco.order.orderId}}</td>
          <td>{{acco.order.status}}</td>
          <td>{{acco.order.side}}</td>
          <td>{{acco.price|floatformat:4}}</td>
          <td>{{acco.qty|floatformat:4}}</td>
          <td>{{acco.executed_price|floatformat:4}}</td>
          <td>{{acco.order.time|date:'m-d H:i:s'}}</td>
          <td>{{acco.time|date:'m-d H:i:s'}}</td>
        </tr>
        {% endfor %}
        {% for acco in canceled_orders %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <th><a style="text-decoration:none;color: black" href="{%url 'currencies:symbol' acco.symbol.symbol %}">{{acco.symbol.symbol}}</a></td>
          <td>{{acco.orderId}}</td>
          <td>{{acco.status}}</td>
          <td>{{acco.side}}</td>
          <td>{{acco.price|floatformat:4}}</td>
          <td>{{acco.origQty|floatformat:4}}</td>
          <td>0</td>
          <td>{{acco.time|date:'m-d H:i:s'}}</td>
          <td>0</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </small>
  </div>

</div>

{% endblock %}

{% block script%}
<!--取消对应订单 js-->
<script >

for (var i = 0; i <{{openoeders|length}}+1; i++) {
    $("[button_id='"+i+"']").click(function(){
        if(confirm("确认取消订单?")){
        	order_num = $("#cancel_all_orders").find("span")
          var count=$(this).attr('button_id');
          var order_id= $("[order_id="+ count +"]").text();
          var symbol= $("[symbol_id="+ count +"]").text();
          var date_ = {'order_id':order_id,'symbol':symbol};
          $.post("{%url 'qtrading:cancel_order'%}",date_,function(response_date){
            if (response_date.orderId){
              $("tr[order_id="+ response_date.orderId +"]").hide();
              var change = order_num.text()*1-1;
              order_num.text(change);


            }
            else if (response_date.aa){alert('订单取消失败!'+response_date.status);};
          });
        }  
    });
}
</script>
<script>
$("#cancel_all_orders").click(function(){
    if(confirm("确认取消当前所有订单?")){
        for (var i = 1; i <{{openoeders|length}}+1; i++) {
        	order_num = $("#cancel_all_orders").find("span");
          var order_id= $("[order_id="+ i +"]").text();
          var symbol= $("[symbol_id="+ i +"]").text();
          var date_ = {'order_id':order_id,'symbol':symbol};
          $.post("{%url 'qtrading:cancel_order'%}",date_,function(response_date){
            if (response_date.orderId){
              $("tr[order_id="+ response_date.orderId +"]").hide();
              var change = order_num.text()*1-1;
              order_num.text(change);
            };
          }); 
        };
    }  
});

</script>
{% endblock %}