finance/finance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from currencies import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('currencies/',include('currencies.urls')),
    path('qtrading/',include('qtrading.urls')),
    path('reuser/',include('reuser.urls')),
    path('',views.home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/qtrading/urls.py
from django.urls import path
from . import views

app_name = 'qtrading'
urlpatterns = [
    path('',views.qtrading,name='qtrading'),
    path('create_qtrading/',views.create_qtrading,name='create_qtrading'),
    path('qtrading_info/<slug:slug>/',views.qtrading_info,name='qtrading_info'),

    path('trade/',views.trade,name='trade'),

    path('buy_or_sell/',views.buy_or_sell,name='buy_or_sell'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('ceshi/',views.ceshi,name='ceshi'),
] 

finance/reuser/urls.py
from django.urls import path
from . import views

app_name = 'reuser'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('activation/',views.activation,name='activation'),
    path('userview/',views.userview,name='userview'),
]

finance/qtrading/models.py
from django.db import models
from currencies.models import SymbolInfo
from reuser.models import ReUser
# Create your models here.

#量化交易实例
class Qtrading(models.Model):
	account = models.ForeignKey(ReUser,null=True,on_delete=models.CASCADE)
	q_name = models.CharField(max_length=100)
	method = models.CharField(max_length=100)
	symbol = models.ForeignKey(SymbolInfo,null=True,on_delete=models.CASCADE)

	#start_price = models.FloatField(null=True) 
	amount = models.FloatField() #总投入
	q_income = models.FloatField() #波段收益率
	q_amount = models.FloatField() #单笔投入金额
	h_price = models.FloatField() #预估波段高价
	l_price = models.FloatField() #预估波段低价
	iswork = models.BooleanField(default=True) #是否运行
	
	total_account = models.FloatField() #开始时账户市值
	this_price = models.FloatField() #开始时价格
	#this_baseAsset_q = models.FloatField() #开始时基准币的持有量

	simulation_full = models.FloatField(null=True) #模拟计算全仓状态下的收入
	relatively_empty = models.FloatField(null=True) #模拟空仓状态下的收入
	quantitative_i = models.FloatField(null=True) #量化收入
	actual_i = models.FloatField(null=True) #实际收入

	create_time = models.DateTimeField(auto_now_add=True)

#所有订单
class Order(models.Model):
	account = models.ForeignKey(ReUser,null=True,on_delete=models.CASCADE)
	symbol = models.ForeignKey(SymbolInfo,null=True,on_delete=models.CASCADE)
	orderId = models.IntegerField(primary_key=True)
	clientOrderId = models.CharField(max_length=100) #自定义订单id
	price = models.FloatField() #叫价单价
	origQty = models.FloatField() #数量
	executedQty = models.FloatField() #成交数量
	status = models.CharField(max_length=100)
	order_type = models.CharField(max_length=100,default='') #订单类型
	side = models.CharField(max_length=100) #卖卖方
	time = models.DateTimeField() #下单时间
	isWorking =models.BooleanField(default=True)
	order_price = models.FloatField(default=0) #总价（price × origQty）

	q_trading = models.ForeignKey(Qtrading,null=True,on_delete=models.CASCADE)
	parent_order = models.CharField(max_length=100,null=True)
	alter_time = models.DateTimeField(auto_now=True)
class CancelStandbyOrders(models.Model):
	orderid = models.ForeignKey(Order,on_delete=models.CASCADE)


#所有交易
class Trade(models.Model):
	trade_id = models.IntegerField(primary_key=True) #交易id
	account = models.ForeignKey(ReUser,null=True,on_delete=models.CASCADE)
	order = models.ForeignKey(Order,on_delete=models.CASCADE) 
	price = models.FloatField() #交易价格
	qty = models.FloatField() #交易数量
	#bass_usdt_price = models.FloatField()
	commission = models.FloatField() #手续费币消耗数量
	commissionAsset = models.CharField(max_length=100,) #手续费币种
	#bass_commission_price = models.FloatField(null=True,default=0)
	#executed_commission_price = models.FloatField(null=True,default=0)
	time = models.DateTimeField() #交易时间
	isbuyer = models.BooleanField() #是否为买方
	isMaker = models.BooleanField(default=True)
	isBestMatch = models.BooleanField(default=True)
	executed_price = models.FloatField() #交易总价（= price × qty）
	q_trading = models.ForeignKey(Qtrading,null=True,on_delete=models.CASCADE)

finance/qtrading/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.utils import timezone
from django.contrib import auth,messages
from reuser.models import ReUser
from qtrading.models import Qtrading,Order,Trade,CancelStandbyOrders
from currencies.models import Asset,DepositDetails,SymbolInfo,AccountInfo
from django.core.paginator import Paginator 
# Create your views here.
from binance.client import Client
from binance.exceptions import BinanceAPIException

from django.db.models import Q,Count,Sum,functions
from django.contrib.auth.decorators import login_required 
from django.views.decorators.csrf import csrf_exempt

import datetime
import qtrading.tasks as bias
from finance.utils import AssistFun,page_fun

@login_required
def qtrading(request):
    context ={}
    context['qtradings'] = Qtrading.objects.filter(account=request.user).order_by('-create_time')[:10]
    return render(request,'qtrading/qtrading.html',context)

@login_required
@csrf_exempt
def create_qtrading(request):
    context={}
    errors=[]
    symbol_list=['BTCUSDT','BNBUSDT']
    
    if request.method == 'POST':
        
        q_name=request.POST.get('q_name')
        method=request.POST.get('method')
        symbol=request.POST.get('symbol')
        #start_price=float(request.POST.get('start_price'))
        amount=float(request.POST.get('amount'))
        q_income=float(request.POST.get('q_income'))
        q_amount=float(request.POST.get('q_amount'))
        h_price = request.POST.get('h_price')
        l_price = request.POST.get('l_price')
        
        if Qtrading.objects.filter(account=request.user).filter(Q(symbol_id=symbol,iswork=True)|Q(q_name=q_name)):
            messages.warning(request,'此类量化交易实例已经建立(一个市场只能建立一个实例，且不可重名！)')

        else:
            s_list = ['BNBUSDT']
            s_list.append(symbol)
            symbol_list = list(set(s_list))

            api_key = request.user.apikey
            api_secret = request.user.Secret
            client = Client(api_key, api_secret)
            assf = AssistFun(request.user.id,client,symbol_list)
            assf.Up_inventory()
            account_info = AccountInfo.objects.filter(account=request.user,total__gt=0)
            total_account = account_info.aggregate(Sum('market_value'))['market_value__sum']
            
            ifo = client.get_symbol_ticker(symbol=symbol)
            this_price = float(ifo['price'])

            q_t = Qtrading(account=request.user,q_name=q_name,method=method,symbol_id=symbol,
                amount=amount,q_income=q_income,q_amount=q_amount,h_price=h_price,l_price=l_price,
                this_price=this_price,total_account=total_account).save()
        
            #q_t=Qtrading.objects.get(id=10)
            if Qtrading.objects.filter(account=request.user,iswork=1).count() == 1:
                bias.q_start_.delay(request.user.id)
            return HttpResponseRedirect('/qtrading/')

    context['symbol_list'] = symbol_list
    return render(request,'qtrading/create_qtrading.html',context)

@login_required
@csrf_exempt
def qtrading_info(request,slug):
    context = {}
    api_key = request.user.apikey
    api_secret = request.user.Secret
    client = Client(api_key, api_secret)
    q_trading = Qtrading.objects.get(account=request.user,id=slug)

    #关闭实例---------------------
    if request.method == 'POST':
        slug_q_t = q_trading
        slug_q_t.iswork = False
        slug_q_t.save()
        CancelStandbyOrders.objects.filter(orderid__q_trading_id=slug).delete()
        try:
            ifo = client.order_limit_buy(symbol='BNBUSDT',quantity=2,price='5')
            ifo_= client.cancel_order(symbol='BNBUSDT',orderId=ifo["orderId"])
        except:
            pass
        return HttpResponseRedirect('/qtrading/')

    trading_stream = Trade.objects.filter(account=request.user,q_trading_id=slug)
    all_orders  = Order.objects.filter(q_trading__id=slug)

    s_list = ['BNBUSDT']
    s_list.append(q_trading.symbol_id)
    symbol_list = list(set(s_list))
    
    

    assf = AssistFun(request.user.id,client,symbol_list)
    #assf.all_orders()

    #计算交易完成对数--------------------------------------------------
    assf.Up_inventory()
    assf.all_access()
    context['total_info'] = assf.totle_inventory()
    account_info = AccountInfo.objects.filter(account=request.user,total__gt=0)

    context['account_info'] = account_info.order_by('-market_value')

    if q_trading.iswork:
        actual_i = account_info.aggregate(Sum('market_value'))['market_value__sum']-q_trading.total_account

        asset_price = Asset.objects.get(name=q_trading.symbol.baseAsset).price
        price_fluncuation = (float(asset_price)-q_trading.this_price)

        simulation_i = price_fluncuation*(q_trading.amount/q_trading.this_price)

        #quantitative_i2 = actual_i - price_fluncuation*q_trading.this_baseAsset_q

        commission = trading_stream.values('commissionAsset').annotate(Sum("commission"))
        commission_cost = sum([each['commission__sum']*Asset.objects.get(name=each['commissionAsset']).price for each in commission])

        #print(quantitative_i2,'----------',commission_cost)
        t_c = trading_stream.filter(isbuyer=True).aggregate(Sum("executed_price"))['executed_price__sum']
        if not t_c:t_c = 0
        f_c = trading_stream.filter(isbuyer=False).aggregate(Sum("executed_price"))['executed_price__sum']
        if not f_c:f_c = 0
        buy_qty__sum = trading_stream.filter(isbuyer=True).aggregate(Sum("qty"))['qty__sum']
        if not buy_qty__sum:buy_qty__sum = 0
        sell_qty__sum = trading_stream.filter(isbuyer=False).aggregate(Sum("qty"))['qty__sum']
        if not sell_qty__sum:sell_qty__sum = 0

        quantitative_i =(f_c-t_c)+float(asset_price)*(buy_qty__sum-sell_qty__sum)-commission_cost
        #context['quantitative_i2']=quantitative_i2


        q_trading.relatively_empty = price_fluncuation*(buy_qty__sum-sell_qty__sum)-commission_cost  #相较于空仓
        q_trading.quantitative_i = quantitative_i  #量化收益
        q_trading.simulation_full = quantitative_i-simulation_i #相较于满仓
        q_trading.actual_i = actual_i  #实际收益
        q_trading.save() 

    f_pair={} 
    filled      = all_orders.filter(status='FILLED').values('parent_order').annotate(o_count=Count('parent_order'))
    filled_pair = filled.filter(o_count=2).count()
    f_pair['filled_pair']        = filled_pair
    f_pair['filled_pair_amount'] = filled_pair*q_trading.q_amount
    f_pair['buy_pair']           = all_orders.filter(status='NEW',side='BUY').count()
    f_pair['sell_pair']          = all_orders.filter(status='NEW',side='SELL').count()
    f_pair['buy_pair_amount']    = all_orders.filter(status='NEW',side='BUY').aggregate(Sum('order_price'))['order_price__sum']
    f_pair['sell_pair_amount']   = all_orders.filter(status='NEW',side='sell').aggregate(Sum('origQty'))['origQty__sum']
    f_pair['actual_i']           = q_trading.actual_i
    f_pair['relatively_empty']   = q_trading.relatively_empty
    f_pair['simulation_full']       = q_trading.simulation_full
    f_pair['quantitative_i']     = q_trading.quantitative_i
    f_pair['complete_new']       = all_orders.filter(status='NEW').values('parent_order').annotate(o_count=Count('parent_order')).filter(o_count=2).count()
    
    context['f_pair']            = f_pair
    
    #当前委托（NEW）深度图,数据
    chartdate1 = {}
    new_orders = all_orders.filter(status='NEW').values_list('price').annotate(volume=Sum('order_price'))
    chartdate1['bids'] = [list(i) for i in new_orders.filter(side='BUY')]
    chartdate1['asks'] = [list(i) for i in new_orders.filter(side='SELL')]
    context['chartdate1']        = chartdate1

    #买卖成交（/5min），数据
    chartdate3=[] 
    now_time = timezone.datetime.utcnow().replace(tzinfo=timezone.utc)
    start_time = now_time-datetime.timedelta(minutes=185)
    if start_time < q_trading.create_time:
        start_time = q_trading.create_time

    time_count = round((now_time - start_time )/datetime.timedelta(minutes=5),0)
    all_orders2 = Order.objects.filter(q_trading__id=slug).exclude(parent_order='Start').select_related()
    for i in range(int(time_count)):
        chartdate3_={}
        start_time += datetime.timedelta(minutes=5)
        chartdate3_['date'] = (start_time+datetime.timedelta(hours=8)).strftime("%H:%M")
        all_orders_filled = all_orders2.filter(alter_time__lte=start_time,status='FILLED')
        chartdate3_['filled_pair'] = all_orders_filled.values('parent_order').annotate(o_count=Count('parent_order')).filter(o_count=2).count()
        if i !=0:
            chartdate3_['filled_pair_each'] = chartdate3_['filled_pair'] -  chartdate3[-1]['filled_pair'] 
        else:
            chartdate3_['filled_pair_each'] = chartdate3_['filled_pair']
        chartdate3_["filled_buy_"] = all_orders_filled.filter(side='BUY').count()
        if i !=0:
            chartdate3_['filled_buy'] = chartdate3_['filled_buy_'] - chartdate3[-1]['filled_buy_'] 
        else:
            chartdate3_['filled_buy'] = chartdate3_['filled_buy_']
        chartdate3_["filled_sell_"] = all_orders_filled.filter(side='SELL').count()
        if i !=0:
            chartdate3_['filled_sell'] = chartdate3_['filled_sell_'] -  chartdate3[-1]['filled_sell_'] 
        else:
            chartdate3_['filled_sell'] = chartdate3_['filled_sell_']
        if i == (int(time_count)-1):
            chartdate3_["bulletClass"]= "lastBullet"
        all_orders_new = all_orders2.filter(time__lte=start_time).exclude(status='CANCELED')
        chartdate3_['new_buy'] = all_orders_new.filter(side='BUY').count() -chartdate3_['filled_buy_']
        chartdate3_['new_sell'] = all_orders_new.filter(side='SELL').count() -chartdate3_['filled_sell_']
        chartdate3.append(chartdate3_)


    context['chartdate3'] = chartdate3[-36:]


    context['all_orders']        = all_orders.order_by('-parent_order','-time')[:100]

finance/qtrading/templates/qtrading/create_qtrading.html
{% extends 'base.html' %}
{%load static%}

{% block title %}   {% endblock %}

{% block content%}


{% if errors %}
<div class="alert alert-danger" role="alert">
    {% for error in errors %}
    <p style="color: red;">
        {{error}}
    </p>
    {% endfor %}
</div>
{% endif %}


<div class="form-group">
  <h2><p class="text-center"><span style="text-decoration:line-through;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
    创建量化交易程序 <span style="text-decoration:line-through;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
  </p></h2>
</div>
<hr>
<br>

<form class="was-validated" enctype="multipart/form-data" method="post">{% csrf_token %}
  <div style="margin: 10px -5px;" class="mb-3 biankuang">
  <div class="form-group  row" >
    <label for="inputEmail3" class="col-sm-2 col-form-label">量化交易名称</label>
    <div class="col-sm-9 ">
      <input type="text" class="form-control is-invalid" id="" placeholder="例:0601BTCUSDT" name="q_name" required >
    </div>
  </div>


  <div class="form-group row" >
    <label for="inputEmail3" class="col-sm-2 col-form-label">选择量化交易模式</label>
    <div class="col-sm-9">
        <select class="custom-select" name="method">
        <option value='波段捕手'>波段捕手</option>
        <option value='方法一'>方法一</option>
        </select>
    </div>
  </div>

  <div class="form-group row" >
    <label for="inputEmail3" class="col-sm-2 col-form-label">选择交易对</label>
    <div class="col-sm-9">
        <select class="custom-select" name="symbol">
          {% for each in symbol_list %}
          <option value='{{each}}'>{{each}}</option>
          {% endfor %}
        </select>
    </div>
  </div>
  </div>

  <div class=" mb-3 " style="box-shadow:5px 5px 20px rgba(0, 0, 0, 0.1) ;padding: 20px;margin: 10px -5px;text-align: center;color: #dc3545;">
  合理资金利用公式：(1+P)^(T/(U*N))=Pmax/Pmin
  </div>

  <div class="form-row mb-3 biankuang" >
    <div class="col-sm-5 ">
      <label for="">投入金额:T</label>
      <div class="input-group ">
        <input type="number" class="form-control" id="" placeholder="您目前持有{{usdr_free}}USDT" aria-describedby="inputGroupPrepend" required min="100" name="amount" >
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2">USDT</span>
        </div>
        <div class="invalid-feedback">
          <small>建议金额不低于2000USDT!</small>
        </div>
      </div>
    </div>
    <div class="col-sm-5 offset-sm-2 ">
      <label for="validationCustom01">交易对 进场价格</label>
      <input type="number" class="form-control" id="" placeholder="" value="0" required  min="0" step="0.01" name="start_price">
      <div class="valid-feedback">
        
      </div>
    </div>
  </div>

  <div class="form-row mb-3 biankuang" >
    <div class="col-sm-5 ">
      <label for="">预测市场波动高价:Pmax</label>
      <input type="number" class="form-control" id="" placeholder="" value="" required min="0"  step="0.0001" name="h_price">
      <div class="invalid-feedback">
        <small>依市场走势大致判断</small>
      </div>
    </div>
    <div class="col-sm-5 offset-sm-2 ">
      <label for="">预测市场波动低价:Pmin</label>
      <input type="number" class="form-control" id="" placeholder="" value="" required min="0" step="0.0001" name="l_price">
      <div class="invalid-feedback">
        <small>依市场走势大致判断</small>
      </div>
    </div>
  </div>

  <div class="form-row mb-3 biankuang" >
    <div class="col-sm-5 ">
      <label for="validationCustom02">量化交易单组收益:O</label>
      <input type="number" class="form-control" id="validationCustom02" placeholder="" value="{{x}}" required min="0.002" max="0.5" step="0.0001" name="q_income">
      <div class="invalid-feedback">
        建议不低于0.002！
      </div>
      <div class="valid-feedback">
        
      </div>
    </div>

    <div class="col-sm-5 offset-sm-2 ">
      <label for="">量化交易单笔金额:U</label>
      <div class="input-group ">
        <input type="number" class="form-control" id="" placeholder="" aria-describedby="inputGroupPrepend"  required min="11" name="q_amount">
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2">USDT</span>
        </div>
        <div class="invalid-feedback">
          <small>不得低于11USDT!</small>
        </div>
      </div>
    </div>
  </div>





  <div class="custom-control custom-checkbox mb-3">
    <input type="checkbox" class="custom-control-input" id="customControlValidation1" required>
    <label class="custom-control-label" for="customControlValidation1">同意条款</label>
    <div class="invalid-feedback">量化交易程序为辅助交易程序，您应熟知程序优劣势。</div>
  </div>

  <br>
  <br>
  
  <div class="d-flex justify-content-around" >
    <button type="submit" class="btn btn-success">创建此程序</button>
  </div>


</form>
{% endblock %}

finance/qtrading/templates/qtrading/qtrading.html
{% extends 'base.html' %}
{%load static%}

{% block title %} 量化交易 {% endblock %}

{% block content%}

<div class="card" style="margin-bottom: 20px;">
  <div class="card-body">
    <div class="row" >
      <div class="col-sm-2">
        <div class="list-group" id="list-tab" role="tablist">
          <a class="list-group-item list-group-item-action list-group-item-light active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">波段捕手</a>
          <a class="list-group-item list-group-item-action list-group-item-light" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">趋势买卖</a>
          <a class="list-group-item list-group-item-action list-group-item-light" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">组合策略</a>
        </div>


      </div>
      <div class="col-sm-10"  style="height: 200px;overflow:auto">
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list" >
            策略名称：波段捕手<br>
            策略目的：利用波段浮动，自动赚取收益<br>
            初始条件：<br>
            1、设定此量化交易总投入USDT量(T)<br>
            2、预测市场高价、低价(Pmax、Pmin)<br>
            3、设定变量，波段收益：O，单笔金额：U<br>
            4、依合理资金利用公式，计算变量设置是否合理<br>
            运行规则：<br>
            1、手动下一单以上（N）起始单，成交后按照O计算价格，触发一组（一买一卖）订单，<br>
            买单价=触发单的价格*((1+O)^0.5)<br>
            卖单价=触发单的价格*1/((1+O)^0.5)<br>
            2、每组订单先完成的单将按此价格触发新的一组订单，同组后完成的另一单不触发。<br>
            3、订单触发后进行边界处理：将要触发的卖单超过前期最高成交价Pmax或者买单超过前期最低价Pmin，视为触发边界<br>
            下一组订单的卖价超过最高价，只下卖单，不下买单，卖单成交之后再补下买单<br>
            下一组订单的买价低于最低价，只下买单，不下卖单，买单成交之后再补下卖单<br>
          </div>
          <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">2</div>
          <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">3</div>
        </div>
      </div>
    </div>
    <br>
    <div  class="row justify-content-around">
      <div class=" col-sm-3" >
        <a href="{% url 'qtrading:create_qtrading' %}" class="btn btn-success">创建新的量化交易程序</a>  
      </div>
    </div>
  </div>
</div>

<div class="card">
  <h5 class="card-header">您目前的量化交易程序</h5>
  <div class="card-body">
    {% for each in qtradings %}
      {%if each.iswork %}
      <div class="alert alert-success row xiewen progress-bar-animated" role="alert" >
        <div class="col-sm-3" style="text-align: center;">
          <a href="{%url 'qtrading:qtrading_info' each.id %}"> <b>{{each.q_name}}</b><small class="text-muted" >-({{each.symbol_id}})</small> </a>
        </div>
        <div class="col-sm-7 row justify-content-around " style="text-align: center;" >
          <div class="col-sm-3">
            <small class="text-success">正在运行...</small>
          </div>
        </div>
        <div class="col-sm-2" style="text-align: right;">
          <small class="text-muted" >{{each.create_time|date:'m-d H:i:s'}}</small>
        </div>
      </div>
      {% else %}
      <div class="alert alert-secondary row xiewen" role="alert" >
        <div class="col-sm-3" style="text-align: center;">
          <a href="{%url 'qtrading:qtrading_info' each.id %}" class="text-muted"> <b>{{each.q_name}}</b><small >-({{each.symbol_id}})</small> </a>
        </div>
        <div class="col-sm-7  row" style="text-align: center;" >
            <div class=" col-sm-3" >
              <span class="badge  badge-info">相较于空仓&nbsp;&nbsp;{{each.relatively_empty|floatformat:2}}USDT</span>
            </div>
            <div class=" col-sm-3" >
              <span class="badge  badge-info">相较于满仓&nbsp;&nbsp;{{each.simulation_full|floatformat:2}}USDT</span>  
            </div> 
            <div class=" col-sm-3" >
              <span class="badge  badge-danger" >量化收益&nbsp;&nbsp;{{each.quantitative_i|floatformat:2}}USDT</span>  
            </div>
            <div class=" col-sm-3" >
              <span class="badge  badge-success">实际收益&nbsp;&nbsp;{{each.actual_i|floatformat:2}}USDT</span>  
            </div>
        </div>
        <div class="col-sm-2" style="text-align: right;">
          <small class="text-muted" >{{each.create_time|date:'m-d H:i:s'}}</small>
        </div>
      </div>
      {% endif %}
    {% endfor %}
    </div>

</div>

{% endblock %}